# coding: utf-8
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ios' do
  # pod 'IJKPlayerSDK', :path => '/Users/cong/repos/app_ios_livesdk/IJKPlayerSDK/libIJKPlayerSDK'
end
